 import './../css/index.css';
 import "./../css/About.css";
 import restaurantPic from "../images/restaurant2.png";
 import restaurant1 from "../images/restaurant1.png";

 const About = () => {
    return (
    <main id="main-content" className="columns">
             <ol>
                <li id="about-columns">
                    <div className="flex-item">
                        <h3>Hours</h3>
                        <div id="time-table">
                            <ol>
                                <li>Monday </li>
                                <li> Tuesday </li>
                                <li>Wednesday </li>
                                <li>Thursday </li>
                                <li>Friday </li>
                                <li>Saturday </li>
                                <li>Sunday </li>
                            </ol>
                            <ol>
                                <li>    11-9</li>
                                <li>    11-9</li>
                                <li>    11-9</li>
                                <li>    11-9</li>
                                <li>    11-11</li>
                                <li>    11-10</li>
                                <li>    12-8:30</li>
                            </ol>
                        </div>
                    </div>
                    <div className="flex-item">
                        <h3>Location</h3>
                        <p>000 Some St</p>
                        <p>Suite 00</p>
                        <p>SomeCity, FL 00000</p>
                        <section id = "map" className="one">
                            <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11533.25629288421!2d-81.29078733984252!3d29.89864135920349!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88e6825775df7f4f%3A0xc2a183178b276027!2sSt.%20Augustine%2C%20FL!5e0!3m2!1sen!2sus!4v1760457031373!5m2!1sen!2sus" width="600" height="450" style={{border: 0}} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>
                        </section>
                    </div>
                </li>
                <li>
                    <h2 id="started-header">How We Got Started</h2>
                    <section className="started">
                        {/*image and paragraph generated by chat gpt*/}
                        <p id="p1">Our story began with a love for the flavors and traditions of Portugal. Growing up surrounded by family recipes passed down through generations, we wanted to bring that same warmth and authenticity to our community here in America. What started as small gatherings with friends and neighbors quickly grew into a dream of opening a place where anyone could experience the taste of Portugal—fresh seafood, savory grilled meats, and of course, the comfort of homemade bread and wine shared around the table.</p> 
                        <img src={restaurant1} className="about-images" alt="restaurant" />
                    </section>
                </li>
                <li class="started">
                    {/*image and paragraph generated by chat gpt-*/}
                    <img className="about-images"src={restaurantPic} alt="restaurant interior" />
                    <p id="p2">When we opened our doors, our goal was simple: to create more than just a restaurant. We wanted to build a space where guests could feel at home, enjoy the richness of Portuguese culture, and celebrate life over a good meal. From the music of fado softly playing in the background to the aromas drifting from our kitchen, every detail is inspired by the cafés and tavernas of Lisbon and Porto. Today, we’re proud to share our heritage with every guest who walks in, and to continue a tradition of hospitality that is at the heart of who we are.</p> 
                </li>
            </ol>
        </main>
    );
};

export default About;