import './../css/index.css';
import "./../css/Home.css";
import welcomePic from "../images/gpt-fado.png";
import tartPic from "../images/tart.jpg";
import socialPic from "../images/social2.jpg";
    function Home() {
      return (
        <main id = "about" className="main-content">
            <section class="welcome">
                <div>
                    <h2>Welcome</h2>
                    {/*paragraph generated by chat gpt*/}
                    <p>Welcome to Casa de Franco- A Taste of Portugal in the Heart of America! Step into our kitchen and experience the rich traditions, bold flavors, and warm hospitality of Portuguese cuisine. From our freshly baked pão and sizzling seafood to our signature peri-peri dishes and beloved pastéis de nata, every bite tells a story. Whether you're here for a casual lunch, a romantic dinner, or a family gathering, we invite you to relax, savor, and enjoy the best of Portugal — no passport required.</p>
                    <button class="reserve-btn"><a href="contact.html">Reserve Your Table</a></button>
                </div>
                <div class="welcome-image">
                    <img src={welcomePic}/>
                </div>
            </section>

            {/* Social Media */}
            <section class="social">
                <h2>Follow Us on Social Media</h2>
                <div class="social-content">
                    <ul class="social-links">   {/*will be made dummy links later*/}
                        <li><a href="#">Tiktok</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Twitter</a></li>
                        <li><a href="#">Instagram</a></li>
                    </ul>
                    <div class="social-images">
                        <img src={tartPic}/>
                        <img src={socialPic}/>
                    </div>
                </div>
            </section>
        </main>
      );
    }

    export default Home;